#!/bin/sh
# Wazuh executes the extension-less name; this hands off to the Python script
# using the interpreter bundled with the Wazuh manager.
WPYTHON_BIN="framework/python/bin/python3"

SCRIPT_PATH_NAME="$0"
DIR_NAME="$(cd "$(dirname "$SCRIPT_PATH_NAME")" >/dev/null 2>&1 && pwd)"
SCRIPT_NAME="$(basename "$SCRIPT_PATH_NAME")"

case "$DIR_NAME" in
    */active-response/bin | */wodles*)
        if [ -z "$WAZUH_PATH" ]; then
            WAZUH_PATH="$(cd "$DIR_NAME/../.." >/dev/null 2>&1 && pwd)"
        fi
        PYTHON_SCRIPT="$DIR_NAME/$SCRIPT_NAME.py"
        ;;
    */bin)
        if [ -z "$WAZUH_PATH" ]; then
            WAZUH_PATH="$(cd "$DIR_NAME/.." >/dev/null 2>&1 && pwd)"
        fi
        PYTHON_SCRIPT="$WAZUH_PATH/framework/scripts/$SCRIPT_NAME.py"
        ;;
    */integrations)
        if [ -z "$WAZUH_PATH" ]; then
            WAZUH_PATH="$(cd "$DIR_NAME/.." >/dev/null 2>&1 && pwd)"
        fi
        PYTHON_SCRIPT="$DIR_NAME/$SCRIPT_NAME.py"
        ;;
esac

"$WAZUH_PATH/$WPYTHON_BIN" "$PYTHON_SCRIPT" "$@"
