#!/usr/bin/env bash
#
# Legion installer.
#
#   ./install.sh
#
# Generates the secrets this installation needs, writes .env, and starts
# everything with Docker. Safe to re-run: existing secrets are kept, because
# regenerating JWT_SECRET would sign every user out and regenerating the
# database password would lock Legion out of its own data.

set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
COMPOSE="docker compose"

say()  { printf '\033[0;36m%s\033[0m\n' "$*"; }
ok()   { printf '\033[0;32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[0;33m!\033[0m %s\n' "$*"; }
die()  { printf '\033[0;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# --- Requirements ------------------------------------------------------------

command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || {
  command -v docker-compose >/dev/null 2>&1 || die "Docker Compose is not available."
  COMPOSE="docker-compose"
}
docker info >/dev/null 2>&1 || die "Cannot talk to the Docker daemon. Is it running, and is your user in the 'docker' group?"

ok "Docker is available"

# --- Secrets -----------------------------------------------------------------

random_hex() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$1"
  else head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}

# Reads a value already present in .env so re-running preserves it.
existing() {
  [[ -f "$ENV_FILE" ]] || return 0
  sed -n "s/^$1=//p" "$ENV_FILE" | head -1
}

JWT_SECRET="$(existing JWT_SECRET)"
POSTGRES_PASSWORD="$(existing POSTGRES_PASSWORD)"
WEBHOOK_SECRET="$(existing SECURITY_EVENT_WEBHOOK_SECRET)"

NEW_INSTALL=false
if [[ -z "$JWT_SECRET" ]]; then
  NEW_INSTALL=true
  JWT_SECRET="$(random_hex 32)"
  POSTGRES_PASSWORD="$(random_hex 16)"
  WEBHOOK_SECRET="$(random_hex 32)"
  say "Generated new secrets"
else
  ok "Existing secrets in $ENV_FILE kept"
fi

# --- Configuration -----------------------------------------------------------

# Everything the customer is likely to change is at the top of the file.
if [[ "$NEW_INSTALL" == true ]]; then
  cat > "$ENV_FILE" <<EOF
# Legion configuration — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Keep this file private and back it up. Losing JWT_SECRET signs everyone out;
# losing POSTGRES_PASSWORD locks Legion out of its own database.

# The address people will open in their browser. Change this to your server's
# name or IP, then re-run ./install.sh.
FRONTEND_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:8000

# Set to true once you have put Legion behind HTTPS (see deploy/nginx.conf).
COOKIE_SECURE=false

# --- Your organisation -------------------------------------------------------
# You run this installation, so the privacy and terms pages describe YOUR
# organisation, not Legion's vendor. Put your name and the address your own
# people should write to here; both appear on those pages. Leave them empty and
# the pages will say so in plain sight.
NEXT_PUBLIC_OPERATOR_NAME=
NEXT_PUBLIC_SUPPORT_EMAIL=

# --- Email (optional) --------------------------------------------------------
# Without SMTP, password-reset and invitation links are printed to the server
# log instead of being emailed: docker compose logs backend
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=Legion <no-reply@example.com>
ALERT_EMAIL_MIN_SEVERITY=high

# --- AI (optional) -----------------------------------------------------------
# Leave both keys empty and Oracle and Copilot fall back to built-in analysis:
# NO alert data leaves your server. Set one and alert titles, summaries,
# hostnames and IPs are sent to that provider for analysis.
#
# OpenRouter reaches many vendors' models with one key, including free ones.
# Pick a model at https://openrouter.ai/models; left empty, your OpenRouter
# account default is used.
OPENROUTER_API_KEY=
OPENROUTER_MODEL=

# Groq is the alternative. If both keys are set, OpenRouter wins unless you
# set AI_PROVIDER=groq.
GROQ_API_KEY=
GROQ_MODEL=llama-3.3-70b-versatile
AI_PROVIDER=

# --- Generated secrets — do not edit ----------------------------------------
DEPLOYMENT_MODE=self-hosted
JWT_SECRET=$JWT_SECRET
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SECURITY_EVENT_WEBHOOK_SECRET=$WEBHOOK_SECRET
EOF
  chmod 600 "$ENV_FILE"
  ok "Wrote $ENV_FILE (permissions 600)"
fi

# --- Start -------------------------------------------------------------------

say "Building and starting Legion — the first run downloads images and may take a few minutes."
$COMPOSE up -d --build

# --- Wait for readiness ------------------------------------------------------

API_URL="http://localhost:8000/health"
printf 'Waiting for Legion to become ready'
READY=false
for _ in $(seq 1 60); do
  if curl -fsS --max-time 2 "$API_URL" >/dev/null 2>&1; then READY=true; break; fi
  printf '.'
  sleep 2
done
printf '\n'

if [[ "$READY" != true ]]; then
  warn "Legion did not report ready within two minutes."
  echo "  Check the logs with:  $COMPOSE logs --tail=50 backend"
  exit 1
fi

ok "Legion is running"

# --- What next ---------------------------------------------------------------

FRONTEND="$(sed -n 's/^FRONTEND_URL=//p' "$ENV_FILE" | head -1)"

cat <<EOF

────────────────────────────────────────────────────────────
  Legion is ready:  ${FRONTEND:-http://localhost:3000}

  Open that address and create the first administrator account.
  Registration closes automatically afterwards — everyone else
  joins by invitation from Settings → Team.

  Connect Wazuh:        see WAZUH.md
  Set up backups:       see BACKUP.md
  Put Legion on HTTPS:  see deploy/nginx.conf

  Useful commands
    $COMPOSE logs -f backend     watch the logs
    $COMPOSE ps                  what is running
    $COMPOSE down                stop Legion
    ./install.sh                 re-run after editing .env
────────────────────────────────────────────────────────────
EOF
