# Legion — start with Docker Desktop (Windows). The PowerShell twin of install.sh.
#
#   In PowerShell, in this folder:
#     powershell -ExecutionPolicy Bypass -File .\start-docker.ps1
#
# What it does: checks Docker Desktop is running, creates the secrets and the
# configuration file (.env) the first time, builds and starts Legion, and waits
# until it answers. Safe to run again: existing secrets are kept, because
# regenerating JWT_SECRET signs every user out and regenerating the database
# password locks Legion out of its own data.

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

function Say($m)  { Write-Host $m -ForegroundColor Cyan }
function Ok($m)   { Write-Host "OK  $m" -ForegroundColor Green }
function Fail($m) { Write-Host "ERR $m" -ForegroundColor Red; exit 1 }

# --- Docker ------------------------------------------------------------------

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Fail "Docker Desktop is not installed. Get it from https://www.docker.com/products/docker-desktop/ , install and start it, then run this again."
}
# cmd /c keeps Docker's messages out of PowerShell's error handling (Windows
# PowerShell 5.1 turns redirected native stderr into a terminating error).
cmd /c "docker info >nul 2>&1"
if ($LASTEXITCODE -ne 0) {
    Fail "Docker Desktop is installed but not running. Start Docker Desktop, wait until it says 'Engine running', then run this again."
}
Ok "Docker is running"

# --- Secrets and configuration -----------------------------------------------

function New-Hex([int]$bytes) {
    $buffer = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buffer)
    return -join ($buffer | ForEach-Object { $_.ToString("x2") })
}
function Existing([string[]]$lines, [string]$name) {
    $match = $lines | Where-Object { $_ -like "$name=*" } | Select-Object -First 1
    if ($match) { return $match.Substring($name.Length + 1) }
    return ""
}

$envPath = Join-Path $PSScriptRoot ".env"
$lines = @()
if (Test-Path $envPath) { $lines = @(Get-Content $envPath -Encoding UTF8) }
$utf8 = New-Object System.Text.UTF8Encoding($false)   # no byte-order mark: docker compose reads it as plain text

$jwt = Existing $lines "JWT_SECRET"
if ($jwt -eq "") {
    $jwt = New-Hex 32
    $pgPassword = New-Hex 16
    $webhook = New-Hex 32
    $keys = "k1:" + (New-Hex 32)
    $stamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $text = @"
# Legion configuration — generated by start-docker.ps1 on $stamp
#
# Keep this file private and back it up. Losing JWT_SECRET signs everyone out;
# losing POSTGRES_PASSWORD locks Legion out of its own database.

# The address people will open in their browser.
FRONTEND_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:8000

# Set to true once you have put Legion behind HTTPS (see DEPLOY-ONLINE.md).
COOKIE_SECURE=false

# --- Your organisation -------------------------------------------------------
# Shown on the privacy and terms pages. Leave empty and the pages say so.
NEXT_PUBLIC_OPERATOR_NAME=
NEXT_PUBLIC_SUPPORT_EMAIL=

# --- Email (optional) --------------------------------------------------------
# Without SMTP, password-reset and invitation links are printed to the log:
#   docker compose logs backend
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=Legion <no-reply@example.com>
ALERT_EMAIL_MIN_SEVERITY=high

# --- AI (optional) -----------------------------------------------------------
# Leave both empty and analysis stays on your computer. Set one and alert
# details are sent to that provider.
OPENROUTER_API_KEY=
OPENROUTER_MODEL=
GROQ_API_KEY=
GROQ_MODEL=llama-3.3-70b-versatile
AI_PROVIDER=

# --- Generated secrets — do not edit ----------------------------------------
DEPLOYMENT_MODE=self-hosted
JWT_SECRET=$jwt
POSTGRES_PASSWORD=$pgPassword
SECURITY_EVENT_WEBHOOK_SECRET=$webhook
LEGION_ENCRYPTION_KEYS=$keys
"@
    [System.IO.File]::WriteAllText($envPath, $text, $utf8)
    Ok "Created .env with new secrets"
} else {
    Ok "Existing secrets in .env kept"
    if ((Existing $lines "LEGION_ENCRYPTION_KEYS") -eq "") {
        # Installations made before this key existed: add it, keep everything else.
        $addition = "LEGION_ENCRYPTION_KEYS=k1:" + (New-Hex 32)
        [System.IO.File]::AppendAllText($envPath, "`r`n$addition`r`n", $utf8)
        Ok "Added LEGION_ENCRYPTION_KEYS to .env"
    }
}

# --- Build and start ---------------------------------------------------------

Say "Building and starting Legion. The first run downloads images and may take 5-15 minutes."
docker compose up -d --build
if ($LASTEXITCODE -ne 0) {
    Fail "docker compose failed. Read the first red error above; send it to your technical helper if unclear."
}

# --- Wait until it answers ---------------------------------------------------

Write-Host -NoNewline "Waiting for Legion to become ready"
$ready = $false
for ($i = 0; $i -lt 90; $i++) {
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:8000/health" -UseBasicParsing -TimeoutSec 2
        if ($response.StatusCode -eq 200) { $ready = $true; break }
    } catch { }
    Write-Host -NoNewline "."
    Start-Sleep -Seconds 2
}
Write-Host ""
if (-not $ready) {
    Write-Host "Legion did not report ready within three minutes." -ForegroundColor Yellow
    Write-Host "  See the reason with:  docker compose logs --tail=50 backend"
    exit 1
}

$frontend = Existing (Get-Content $envPath -Encoding UTF8) "FRONTEND_URL"
Write-Host ""
Write-Host "------------------------------------------------------------" -ForegroundColor Green
Write-Host "  Legion is ready:  $frontend" -ForegroundColor Green
Write-Host ""
Write-Host "  Open that address and create the first administrator account."
Write-Host ""
Write-Host "  Stop Legion:     docker compose down"
Write-Host "  Start again:     .\start-docker.ps1"
Write-Host "  Watch the logs:  docker compose logs -f backend"
Write-Host "------------------------------------------------------------" -ForegroundColor Green
